name: test
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '*.md'

  pull_request:
    branches:
      - '*'

env:
  GOPROXY: https://proxy.golang.org
  CGO_ENABLED: 0

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint
        run: make lint

      - name: Test
        run: make test
